spring.main.banner-mode=off
spring.main.web-application-type=none
spring.datasource.url=jdbc:sqlite:data/queuectl.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

queuectl.poll-interval-ms=500

logging.level.root=WARN
