spring:
  main:
    banner-mode: "off"
    web-application-type: none
  datasource:
    url: jdbc:sqlite:data/queuectl.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always

queuectl:
  poll-interval-ms: 500

logging:
  level:
    root: WARN
